### PR TITLE
Add CONTRIBUTING and PULL_REQUEST_TEMPLATE

### LINKED ISSUE #15: Needs CONTRIBUTING.md
I propose something like:
---

# How To Contribute To islandora_solr_collection_view

Islandora welcomes community input! You're welcome to contribute by:
* making a pull request against this repo
* using the Github Issues in this repo

By participating in this project, you agree to abide by the Islandora [code of conduct].

[code of conduct]: http://islandora.ca/codeofconduct

## Workflow and merging 

The maintainers of islandora_solr_collection_view may:
* merge anyone's pull requests (except their own, and see note below)
* merge without review
* merge without waiting a courtesy period

As this repository belongs to the Islandora Foundation, anyone contributing code (pull requests) must have a [CLA] on file.

[CLA]: https://github.com/Islandora/islandora/blob/7.x/CONTRIBUTING.md#contribute-code

### PR DESCRIPTION
**Pull request by rosiel**
Fixes #15

# What does this Pull Request do?
Adds required workflow documentation

# What's new?
CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md

# How should this be tested?
Please read and provide feedback!

# Interested parties
@mjordan

### CODE REVIEW

**Review by DiegoPino — APPROVED** [review]
cool. was needed

**Comment by mjordan** [comment]
Excellent, but in CONTRIBUTING.md you say "as defined in this project's README.md" and then go on to specify the merging protocol. Maybe change "as defined in this project's README.md" to "as defined in this project's CONTRIBUTING.md"?

**Comment by DiegoPino** [comment]
@rosiel @mjordan sorry, merged too fast. Should I revert? I was not tagged, my fault. 😿

**Comment by mjordan** [comment]
No biggy, I can open a PR!

**Comment by rosiel** [comment]
Good catch @mjordan!  I accidentally ambiguous. It was supposed to imply that who the maintainer(s) are is in the README. Maybe that's not even necessary. But it definitely shouldnt be worded the way that it is now!

**Pull request merged**
